### ISSUE TITLE
Failed to execute 'start' on 'SpeechRecognition': recognition has already started.

### ISSUE THREAD

**Issue by krisu-pl** [TheMindhouse/memospeak#9]
Steps to reproduce:

1. Enter any text
2. Go to Step 2, do not say anything, press Stop
3. Click again, go to step 2

Expected:
4. App starts new recording

Actual:
4. Error is thrown

![image](https://user-images.githubusercontent.com/7289999/36064039-ba7e111a-0eb7-11e8-90d7-e43e84ce88bc.png)

**Comment by bouzlibop** [comment]
Need more details on this one. Seems to work for me on heroku without an err.

**Comment by krisu-pl** [comment]
Probably fixed with #10

**Comment by micenhat** [comment]
----Solution for issue---

this.recognition = false 
async handleStart(knowledge) {
this.speech.onstart = ()=> {
      console.warn("Voice recognition started. Try speaking into the microphone.");
 	this.recognition = true
};
   if(!this.recognition){
	await this.speech.start();
   }
}
async handleStop() {
    if (this.speech !== undefined) {
      await this.speech.stop();
    }
		
	this.recognition = false
  }
this.speech.onend = (event) => {
	this.recognition = false
};

**Comment by ashutosh321607** [comment]
> ----Solution for issue---
> 
> this.recognition = false
> async handleStart(knowledge) {
> this.speech.onstart = ()=> {
> console.warn("Voice recognition started. Try speaking into the microphone.");
> this.recognition = true
> };
> if(!this.recognition){
> await this.speech.start();
> }
> }
> async handleStop() {
> if (this.speech !== undefined) {
> await this.speech.stop();
> }
> 
> ```
> this.recognition = false
> ```
> 
> }
> this.speech.onend = (event) => {
> this.recognition = false
> };

@micenhat I am facing the same issue mentioned by @krisu-pl but not able to understand how to resolve it. I have tried to understand your code but still the same issue in angular, here is my code,
```
import { Injectable } from '@angular/core';

declare var webkitSpeechRecognition: any;

@Injectable({
  providedIn: 'root',
})
export class VoiceRecognitionService {
  recognition = new webkitSpeechRecognition();
  isStoppedSpeechRecog = true;
  tempWords = '';

  constructor() {}

  init(language) {
    this.recognition.interimResults = true;
    this.recognition.continuous = true;
    this.recognition.lang = language;
    this.recognition.maxAlternatives = 1;
    this.recognition.addEventListener('result', (e) => {
      const results = Array.from(e.results);
      const transcript = e.results[0].isFinal
        ? results[results.length - 1][0].transcript
        : Array.from(e.results)
            .map((result) => result[0])
            .map((result) => result.transcript)
            .join('');
      this.tempWords = transcript;
    });
  }

  start() {
    this.isStoppedSpeechRecog = false;
    this.recognition.start();
    this.tempWords = '';
    console.log('Speech recognition started');
    this.recognition.addEventListener('end', (condition) => {
      if (this.isStoppedSpeechRecog) {
        this.recognition.stop();
        console.log('End speech recognition');
      } else {
        this.recognition.start();
      }
    });
  }

  stop() {
    this.isStoppedSpeechRecog = true;
    this.recognition.stop();
    console.log('End speech recognition');
  }

  changeLanguage(new_language) {
    this.recognition.lang = new_language;
  }
}

```
can you pls help me out with this.
